title: 8Roms
description: Your favourite Roms and games in the sme place
remote_theme: julianolf/jekyll-theme-8bit
logo: nes-kirby
show_downloads: true
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
paginate: 2
social:
  gmail: mailto:consultas@8roms.io
disqus:
  shortname: 8ROMS
